title:  WorkHour
tagline:  Ayuda para la aplicación WorkHour
author:
  name: "Cecilio Fdz."
  twitter:  kontask

menu:
- {name: 'Post', url: 'writing.html'}
- {name: 'Contacto', url: 'contact.html'}
- {name: 'Acerca de...', url: 'about.html'}

social:
- {icon: 'github', link: 'https://www.github.com/ceciliofdz'}
#- {icon: 'twitter', link: 'https://twitter.com/kontask'}
#- {icon: 'instagram', link: 'https://instagram.com/kontask'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/ceciliofdz/'}
- {icon: 'envelope', link: 'mailto:cecilio.fdz@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
